conradtchan/jobmon

backend/bobmon.py
frontend/src/App.js

the UserPie graph sits at 100% used when there are a bunch of bonus
cores being used. try to fix this by adding to avail cores/nodes in
a similar way to how we add to used.
ie. if a job is using a core on a "bonus" node, then add that node to
the available count and add all the node's cores to available too.
on server side this is for history graph scaling (I think).
on client side it's for the UserPie.

improve bonus node and core accounting

---

frontend/src/config.js

When restarting after a crash, it takes around 10 minutes to load in all the new data. This change prevents the maintenance message from appearing prematurely.

Change default maintenance trigger to 20 minutes

---

frontend/src/App.jsx
frontend/src/UserPiePlot.jsx

Bug: interface was delaying when to show warned users.
Resolved by forcing update after history data is downloaded, and adding to shouldComponentUpdate.

Fix warning delay

---

.github/workflows/node.js.yml

```
opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
[38](https://github.com/conradtchan/jobmon/actions/runs/4684110744/jobs/8299900501#step:4:39)
library: 'digital envelope routines',
[39](https://github.com/conradtchan/jobmon/actions/runs/4684110744/jobs/8299900501#step:4:40)
reason: 'unsupported',
[40](https://github.com/conradtchan/jobmon/actions/runs/4684110744/jobs/8299900501#step:4:41)
code: 'ERR_OSSL_EVP_UNSUPPORTED'
```
Solution is to use `--openssl-legacy-provider`
See: https://stackoverflow.com/questions/69665222/node-js-17-0-1-gatsby-error-digital-envelope-routinesunsupported-err-os

Fix openssl error with CI

---

.github/workflows/pre-commit.yml
.pre-commit-config.yaml
backend/backend_ozstar.py
backend/showbf.py

Fixes a rare bug if the job has recently crashed. Prevents the frontend from trying to read data from a crashed node.

remove node from layout if the job is running but influx doesn't porting it as up

---

backend/backend_ozstar.py

The influxdb query for lustre jobstats is over 10 minutes, in order to capture infrequently updated stats. This causes long "tails" in the graphs when rates have actually gone to zero but not yet updated.
This PR estimates the typical updating frequency by looking at previous update times, and then uses that to truncate values to zero once they are stale.
Essentially, jobmon has to perform a forward extrapolation of the rates, and this change stops it from extrapolating too far in the absence of data points.

Dynamically adjust window for lustre jobstats frequency

---

backend/backend_ozstar.py

Because IB stats are spoofed, a node may have values in the bucket even when it has died, causing false positives for `node_up`. This is fixed by checking explicitly for the CPU values.

check for "cpu" measurement to confirm if node is up

---

frontend/src/NodeDetails.jsx
frontend/src/NodeOverview.jsx
frontend/src/NodePie.jsx
frontend/src/colours.css
frontend/src/index.css

Additional colours for GPU graphs to distinguish between GPUs. Previously only supported 2 GPUs, now supports 4.

Add support for nodes with 4 GPUs

---

frontend/src/NodeDetails.jsx

There is a check for the presence of GPU data, but this fails when no snapshots have been loaded yet.
A check for the array length fixes this.

Bugfix: frontend crashing when gpu data is not loaded yet

---

backend/backend_ozstar.py

For some request types, ntasks_per_node is 0 and leads to an incorrect calculation for job_mem_request.
Check for htis case and use num_cpus and num_nodes to calculate it otherwise.

Fix memory request for jobs without ntasks_per_node

---

backend/backend_ozstar.py

OzSTAR's lustre jobstat collection tools query at a constant frequency, so there is no need to adjust the derivative window dynamically.

Simplify lustre jobstats querying in response to changes on OzSTAR

---

backend/backend_ozstar.py

Lustre jobstats continue to be an issue because the script on OzSTAR does not update values for a particular job if there has been no I/O.
This PR changes the code to query the counter (not the derivative), and then calculate the derivative in the python backend. Additionally, it allows the initial value of zero to be assumed, in order to capture I/O spikes at the start of the job, which may occur before the first data point is reported.

Fix lustre jobstats on OzSTAR

---

backend/backend_ozstar.py

A job array followed by ... may not be handled correctly if it does not have a comma.
For example,
```
148-150,...
```
is OK, but
```
148-15...
```
resulted in an integer conversion error.
This is fixed by always discarding the last item if `...` is present and the second number is smaller than the first.

Handle edge case with slurm job arrays

---

backend/backend_ozstar.py
frontend/src/warnings.js

Ensure that the GPU layout of a job is consistent with the CPU layout. Discard nodes in the GPU layout that are not present in the CPU layout. Also catch this error to prevent a frontend crash.

Bugfix: GPU layout on OzSTAR

---

backend/backend_ozstar.py

The XFS quota job ID is given as the full job ID, not the array ID.

Fix bug with xfs quota job id string

---

frontend/src/warnings.js

This pull request addresses a critical issue in the frontend application where a crash occurs due to missing data for warnings. The changes implemented in this PR ensure that the application handles scenarios where warning data may not be available, preventing unexpected crashes and improving overall stability.

fix frontend crash caused by missing data for warnings

---

backend/backend_ozstar.py

This pull request addresses an issue with the regular expression used to match the Generic Resource (GRES) format. The previous implementation did not account for the possibility of other resources being listed before the GPU, which could lead to incorrect parsing.

fix: update regex to match GRES format correctly

---

.github/workflows/pre-commit.yml
backend/backend_ozstar.py

This pull request includes a small optimization to the `hostnames` method in `backend/backend_ozstar.py`. The change modifies the InfluxDB query to filter data for the last hour and limit it to the "mem" measurement, reducing the cost of the query.

fix expensive query to gather hostnames from influxdb

---

backend/backend_ozstar.py

This pull request modifies how the InfluxDB query API is used in the `backend/backend_ozstar.py` file, aiming to improve resource management by creating and disposing of the query API client within the scope of each query rather than maintaining a persistent instance.

create a new instance of the influxdb query api for each call

---

backend/backend_ozstar.py
backend/jobmon.service
backend/showbf.py

This PR updates to the `backend` codebase to improve compatibility with the new `pyslurm` API. CPU layouts have been dropped from the `job()` API and now have to be obtained from the newer `Job()` API. This new API also contains the GPU layout, so it no longer needs to be manually read from `scontrol`. This allows the methods used to cache the results of `scontrol` to be removed.
Also updated to use slurm's max memory value passed through the `VMSize` variable, instead of tracking it within jobmon.

Use Jobs() API from pyslurm 24.11

---

backend/backend_ozstar.py

The new API had changed the variable for the array job ID from `array_job_id` to `array_id`. Due to the fallback mechanism, this change was not detected, and array jobs were displaying with the other non-array ID, which is less helpful to users.

Fix array JOB IDs

---

frontend/src/NodeDetails.jsx

The graphs in the RHS pane would include timestamps from when the job was still pending. Aside from displaying incorrect data, this would cause errors with the logic for displaying GPU graphs.
Refactored functions for readability.

Fix graph pending jobs
